#!/bin/bash

dir=".bakkes"

if [ "${1}" = "" ]; then
	echo "Usage:"
	echo "bak <option> <filename>"
	echo ""
	echo "Options:"
	echo "	no option:	Create backup of file. Requires filename"
	echo "-r	restore:	Restores backed up file. Requires filename"
	echo "-l	list:		Lists backed up files"
	echo "-d	delete:		Delete backed up file. Requires filename"
	echo "-da	delete all:	Delete all backed up files"
	exit;
fi

if [ ! -d "${dir}" ]; then
	if [ ! -d "${dir}" ]; then
		mkdir ${dir}
	fi
fi

if [ "${1}" = "-r" ]; then
	target_name=${2}

	if [ "${2: -2:1}" = "_" ]; then
		target_name="${2::-2}"
	fi

	if [ -f ${target_name} ]; then
		rm -rf ${target_name}
	fi
	
	cp -r ${dir}/${2} ${target_name}
	echo "Restored '${2}' to '${target_name}'"
elif [ "${1}" = "-l" ]; then
	ls -Al ${dir}
elif [ "${1}" = "-d" ]; then
	rm -rf ${dir}/${2}
elif [ "${1}" = "-da" ]; then
	rm -rf ${dir}/*	
else
	filename=${1}
	n=1	
	
	end=$((${#filename}-1))	
	if [ "${filename:end:1}" = "/" ]; then
		filename=${filename::-1}
	fi
	
	#echo "Creating backup of '${1}'"
	while [ -f "${dir}/${filename}" ] | [ -d "${dir}/${filename}" ]
	do
		filename="${1}_${n}"
		((n=n+1))		
	done
	cp -r ${1} ${dir}/${filename} && echo "Saved as '${filename}'"
fi